spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  application:
    name: notification
  profiles:
    active: default
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/notifications
    username: postgres
    password: postgres
  devtools:
    livereload:
      enabled: true
topic:
  name:
    consumer: notification

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

server:
  port: 9090