spring:
  datasource:
    username: remotesnail0
    url: jdbc:postgresql://universe.postgres.database.azure.com:5432/customerdb?sslmode=require
    password: P8rRj5miQVlhOY5rM8uvJg
  cloud:
    azure:
      servicebus:
        namespace: <your-servicebus-namespace-name>
        entity-type: queue
        entity-name: <your-servicebus-queue-name>
  config:
    import:
  jpa:
    hibernate:
      ddl-auto: create-drop
eureka:
  client:
    service-url:
      defaultZone: https://nuber-microservice-eureka-server.azuremicroservices.io/eureka
  instance:
    prefer-ip-address: 'true'