spring:
  #cloud:
  #  discovery:
  #    enabled: true
  #  service-registry:
  #    auto-registration:
  #      fail-fast: true
  # config rabbitmq for producer
  #rabbitmq:
  #  host: localhost
  #  port: 5672
  #  username: guest
  #  password: guest
  #  queue: customer.queue
  #  template:
  #    exchange: amq.direct
  #    routing-key: customer.routingkey
  #jpa:
  #  properties:
  #    hibernate:
  #      dialect: org.hibernate.dialect.PostgreSQLDialect
  #  hibernate:
  #    ddl-auto: create-drop
  #  show-sql: true
  application:
    name: customer
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://customer.postgres.database.azure.com:5432/postgres?sslmode=require
    username: customer
    password: Zadina@@123


eureka:
  client:
    service-url:
      defaultZone: https://nuber-microservice-eureka-server.azuremicroservices.io/
server:
  port: 9091


