spring:
  # config rabbitmq for producer
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: customer
  profiles:
    active: default
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/customers
    username: postgres
    password: postgres
  devtools:
    livereload:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9091