spring:
  # config rabbitmq for producer
  #rabbitmq:
  #  host: localhost
  #  port: 5672
  #  username: guest
  #  password: guest
  #  queue: bank.customer
  #  template:
  #    exchange: customer.exchange
  #    routing-key: customer.routingkey
  devtools:
    livereload:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wallet
    username: postgres
    password: postgres

  application:
    name: wallet
  profiles:
    active: default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 2000
