spring:
  data:
    mongodb:
      uri: mongodb+srv://mongodb:mongodb@car-service.ysjcpal.mongodb.net/car-service
      auto-index-creation: true

  application:
    name: car
  profiles:
    active: default
  devtools:
    restart:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8082