spring:
  data:
    mongodb:
      uri: mongodb+srv://user-service:anasab13@cluster0.ekc9rnd.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: user-service
  application:
    name: user-service
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8080