spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
    queue: customer.queue
    template:
      routing-key: customer.routingkey
      exchange: amq.direct

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:postgresql://universe.postgres.database.azure.com:5432/driverdb?sslmode=require
    username: remotesnail0
    password: P8rRj5miQVlhOY5rM8uvJg

  application:
    name: driver

eureka:
  client:
    service-url:
      defaultZone: https://nuber-microservice-eureka-server.azuremicroservices.io/eureka

server:
  port: 8081
