spring:
  cloud:
    discovery:
      enabled: true
    service-registry:
      auto-registration:
        fail-fast: true
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
    queue: customer.queue
    template:
      routing-key: customer.routingkey
      exchange: customer.exchange
    
  devtools:
    livereload:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/driver}
    username: postgres
    password: postgres

  application:
    name: driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081
