spring:

  data:
    mongodb:
      uri: mongodb+srv://mongodb:mongodb@cluster0.lppaw8l.mongodb.net/driver-service
      auto-index-creation: true

  application:
    name: driver
  profiles:
    active: default
  devtools:
    restart:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081