server:
  port: 8761

spring:
  devtools:
    livereload:
      enabled: true

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    server:
      waitTimeInMsWhenSyncEmpty: 0