server:
  port: 8761

spring:
  cloud:
    service-registry:
      auto-registration:
        fail-fast: true
  devtools:
    livereload:
      enabled: true

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
